-- Generator.lua
-- Converts parsed CSV data into Roblox Instances or Lua source.

local Generator = {}

local function getDestination(destinationName: string): Instance?
	local map = {
		Workspace         = workspace,
		ServerStorage     = game:GetService("ServerStorage"),
		ReplicatedStorage = game:GetService("ReplicatedStorage"),
	}
	return map[destinationName]
end

local function sanitiseName(name: string): string
	return (name:gsub("[^%w%s_%-]", "_")):match("^%s*(.-)%s*$")
end

local function luaValue(v): string
	if v == nil   then return "nil"   end
	if v == true  then return "true"  end
	if v == false then return "false" end
	if type(v) == "number" then return tostring(v) end
	return string.format("%q", tostring(v))
end

local function serializeTable(headers: {string}, rows: {any}, indent: string?): string
	indent = indent or "\t"
	local lines = { "{" }

	for i, row in ipairs(rows) do
		table.insert(lines, indent .. "{")
		for _, h in ipairs(headers) do
			table.insert(lines, string.format('%s\t[%q] = %s,', indent, h, luaValue(row[h])))
		end
		table.insert(lines, indent .. "},")
	end

	table.insert(lines, "}")
	return table.concat(lines, "\n")
end

local function generateModuleScript(name, destination, headers, rows)
	local ms = Instance.new("ModuleScript")
	ms.Name = sanitiseName(name)
	ms.Source = string.format(
		"-- Auto-generated by SheetSync | Fox Jet Studios\n\nlocal data = %s\n\nreturn data\n",
		serializeTable(headers, rows)
	)
	local scc, err = pcall(function()
		ms.Parent = destination
	end)
	
	if not scc then
		return nil, "Failed to parent ModuleScript to " .. destination.Name .. ": " .. tostring(err)
	end
	
	return ms
end

local function generateFolderValues(name, destination, headers, rows)
	local root  = Instance.new("Folder")
	root.Name   = sanitiseName(name)

	for i, row in ipairs(rows) do
		local rowName = tostring(row[headers[1]] or ("Row_" .. i))
		local folder  = Instance.new("Folder")
		folder.Name   = sanitiseName(rowName)

		for _, h in ipairs(headers) do
			local val  = row[h]
			local inst

			if type(val) == "number" then
				inst       = Instance.new("NumberValue")
				inst.Value = val
			elseif type(val) == "boolean" then
				inst       = Instance.new("BoolValue")
				inst.Value = val
			else
				inst       = Instance.new("StringValue")
				inst.Value = tostring(val or "")
			end

			inst.Name   = sanitiseName(h)
			inst.Parent = folder
		end

		folder.Parent = root
	end

	root.Parent = destination
	return root, nil
end

local function generateLuaTable(name, destination, headers, rows)
	local sp = Instance.new("Script")
	sp.Name = sanitiseName(name)
	sp.Source = string.format(
		"-- Auto-generated by SheetSync | Fox Jet Studios\n\nreturn %s\n",
		serializeTable(headers, rows)
	)
	
	local scc, err = pcall(function()
		sp.Parent = destination
	end)

	if not scc then
		return nil, "Failed to parent Script to " .. destination.Name .. ": " .. tostring(err)
	end
	
	return sp
end

function Generator.generate(options: any): (Instance?, string?)
	local dest = getDestination(options.destination)
	if not dest then
		return nil, "Unknown destination: " .. tostring(options.destination)
	end

	if #options.rows == 0 then
		return nil, "No data rows to generate (sheet may only have a header row)."
	end

	local name       = options.name or "SheetData"
	local headers    = options.headers
	local rows       = options.rows
	local outputType = options.outputType
	local instance, errorMsg

	if outputType == "ModuleScript" then
		instance, errorMsg = generateModuleScript(name, dest, headers, rows)
	elseif outputType == "Folder + Values" then
		instance, errorMsg = generateFolderValues(name, dest, headers, rows)
	elseif outputType == "Lua Table" then
		instance, errorMsg = generateLuaTable(name, dest, headers, rows)
	else
		return nil, "Unknown output type: " .. tostring(outputType)
	end

	return instance, errorMsg
end

return Generator